import type { ParsedData, CliOptions } from '../types.js';
import type { RenderResult } from '../renderer/svg.js';

export function generateHTML(
    svgResult: RenderResult,
    data: ParsedData,
    opts: CliOptions,
): string {
    const title = opts.title ?? 'ChartForge Export';
    const theme = opts.theme ?? 'dark';
    const isDark = theme !== 'light';

    const bg = isDark ? '#0f0f13' : '#f8f9fa';
    const surface = isDark ? '#18181f' : '#ffffff';
    const border = isDark ? '#2a2a35' : '#e5e7eb';
    const text = isDark ? '#e2e2f0' : '#111827';
    const muted = isDark ? '#6b6b80' : '#6b7280';
    const accent = '#6366f1';

    const now = new Date().toLocaleString();
    const stats = buildStats(data);

    return `<!DOCTYPE html>
<html lang="en" data-theme="${theme}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escHtml(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --bg:      ${bg};
      --surface: ${surface};
      --border:  ${border};
      --text:    ${text};
      --muted:   ${muted};
      --accent:  ${accent};
    }

    body {
      font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 2rem 1rem;
    }

    .container {
      width: 100%;
      max-width: 960px;
    }

    header {
      margin-bottom: 1.5rem;
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: .5rem;
    }

    .title-group h1 {
      font-size: 1.5rem;
      font-weight: 700;
      letter-spacing: -.02em;
    }

    .title-group p {
      color: var(--muted);
      font-size: .8rem;
      margin-top: .25rem;
    }

    .badge {
      font-size: .7rem;
      padding: .25rem .6rem;
      background: color-mix(in srgb, var(--accent) 15%, transparent);
      color: var(--accent);
      border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
      border-radius: 9999px;
      font-weight: 600;
      white-space: nowrap;
      align-self: flex-start;
      margin-top: .2rem;
    }

    .chart-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: 0 4px 24px rgba(0,0,0,.12);
    }

    .chart-card svg {
      width: 100%;
      height: auto;
      display: block;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 1rem;
      margin-bottom: 1.5rem;
    }

    .stat-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1rem 1.25rem;
    }

    .stat-card .label {
      font-size: .75rem;
      color: var(--muted);
      text-transform: uppercase;
      letter-spacing: .06em;
      margin-bottom: .35rem;
    }

    .stat-card .value {
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--text);
    }

    .meta {
      font-size: .75rem;
      color: var(--muted);
      text-align: center;
      margin-top: 1rem;
    }

    .meta a { color: var(--accent); text-decoration: none; }
    .meta a:hover { text-decoration: underline; }

    @media (max-width: 600px) {
      .stats-grid { grid-template-columns: 1fr 1fr; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="title-group">
        <h1>${escHtml(title)}</h1>
        <p>Generated by ChartForge CLI · ${escHtml(now)}</p>
      </div>
      <span class="badge">⬡ ChartForge</span>
    </header>

    <div class="chart-card">
      ${svgResult.svg}
    </div>

    <div class="stats-grid">
      ${stats.map(s => `
      <div class="stat-card">
        <div class="label">${escHtml(s.label)}</div>
        <div class="value">${escHtml(s.value)}</div>
      </div>`).join('')}
    </div>

    <p class="meta">
      Rendered with <a href="https://github.com/anandpilania/chartforge" target="_blank">ChartForge</a>
    </p>
  </div>
</body>
</html>`;
}

function buildStats(data: ParsedData): { label: string; value: string }[] {
    const allVals = data.series.flatMap(s => s.data).filter(v => isFinite(v));
    if (!allVals.length) return [];

    const sum = allVals.reduce((s, v) => s + v, 0);
    const avg = sum / allVals.length;
    const fmt = (v: number) => {
        if (Math.abs(v) >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M`;
        if (Math.abs(v) >= 1_000) return `${(v / 1_000).toFixed(1)}k`;
        return Number.isInteger(v) ? String(v) : v.toFixed(2);
    };

    return [
        { label: 'Data Points', value: String(allVals.length) },
        { label: 'Series', value: String(data.series.length) },
        { label: 'Maximum', value: fmt(Math.max(...allVals)) },
        { label: 'Minimum', value: fmt(Math.min(...allVals)) },
        { label: 'Average', value: fmt(avg) },
        { label: 'Total / Sum', value: fmt(sum) },
    ];
}

function escHtml(s: string): string {
    return s
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}
